#!/bin/sh
git diff --cached --check || exit 1

for f in $(git diff --cached --name-only --diff-filter=ACM); do
    if [ -n "$(git show ":$f" | tail -c1)" ]; then
        echo "Newline final manquant : $f"
        exit 1
    fi
done
