export const UNKNOWN_FIELDS = 'UNKNOWN_FIELDS';
export const VALIDATION_ERROR = 'VALIDATION_ERROR';
export const CONFLICT_ERROR = 'CONFLICT_ERROR';
export const INVALID_PAGINATION = 'INVALID_PAGINATION';

export const THEME_ALREADY_EXISTS = 'THEME_ALREADY_EXISTS';
export const THEME_NOT_FOUND = 'THEME_NOT_FOUND';
export const INVALID_UUID = 'INVALID_UUID';